### PR TITLE
Update for 2 SEGA Saturn titles thumbnails (Snapshots Thumbnails)

### PR DESCRIPTION
**Pull request by 15Tails**
I Apologize if I mess anything up. or did something wrong. I had literally never done this before. I Read through the guide on reddit, but still. I hope I did everything correctly. I Will do my absolute best in the future to get better screenshots. (especially some of the title screens) but for now, there wasn't a lot I wanted to change at the moment.

### CODE REVIEW

**Comment by RobLoach** [comment]
Looks great! thanks for the updates. Any others you would like to add?

**Comment by 15Tails** [comment]
Hmm... Nothing that I can think of at the moment. but will update if I ever do. I just have a lot to do on my hands. lol.

**Comment by 15Tails** [comment]
I am not sure how it takes for approval but I was just wondering. while I haven't gotten anymore screenshots or thumbnails yet. How do I update existing... Submissinos? Commits? Idk what to call them here because I am still new to github. lol

**Comment by 15Tails** [comment]
> Looks great! thanks for the updates. Any others you would like to add?

Is it too late to Update this Pull request? I just found out, that there was a setting I was supposed to disable. (GPU Screenshots) I literally thought I had to take the Screenshots then edit them to the correct proportions. but turns out there was a setting that automatically puts screenshots in the correct height and width. My apologies I didn't know at the time. I Wanted to update them in the correct quality/aspect ratio when given the chance.

**Comment by RobLoach** [comment]
Never too late to make updates :+1:

**Comment by 15Tails** [comment]
> Never too late to make updates 👍

oof. I was going to redo the screenshots but I got sidetracked with others things. and it got too late to do  it. Ugh My Sincerce apologies lol...

**Comment by 15Tails** [comment]
Updated the screenshots. all taken in the correct file proportions every other Saturn thumbnail. Apologies if they look blurry, I enabled a setting on Beetlesaturn to hopefully match the quality of how the screenshots looked. for authenticity purposes. I updated Sonic R (USA, Brazil) while I was at it.

 I Was going to do Megaman 8's gameplay screenshot and Keio Flying Squadron 2 (Europe) but I didn't have the time. and I also wanted to playthrough the entirety of Keio at some point. also NiGHTs into dreams was a debate in my mind as well. but ultimately didn't have time for it.
 
 also wanted to represent Clockwork Knight 2 with the unique horse riding levels (or baro baro as it's called in game... who is actually a donkey instead of a horse) which I accidentally found a level skip trying to get the screenshot.
 
 Overall. I Think It's good for now! also would these changes carry over to other regional version of the games? I'm only just curious. but overall I think this is good.

**Comment by OctopusButtons** [comment]
>  also would these changes carry over to other regional version of the games? I'm only just curious

Basically that has to be done manually with multiple duplicate files and different file names / different region tags in the file name. And where the thumbnail name must match the standard (No Intro or whoever) name in the database.

I wish we had a better system but we don't right now.  An improvement would be intermediary/set coding, where titles {A, B, C, D} could all be mapped to the same thumbnail [X], with those correspondences set in the database and with multiple hash checksums defining the variants.  But the real problem I believe is that the philosophy of the Dump Group databases is to only map one specific SKU (so to speak) to one specific formalized name.  They're only interested in unique standard product ID's, whereas the goal of Libretro/Retroarch is more about library usability and most people would (I think) prefer any approx variant region screenshot rather than *no thumbnail.*  Different dumps of the same exact game (same "SKU" so to speak) get mapped, by database of hash checksums, to the same uniform title ...ideally we would want a similar method for mapping game variants to any loosely appropriate thumbnail without proliferating 20 different thumbnail names/files.

**Comment by 15Tails** [comment]
Wasn't expecting an notification on this old pull request. but no worries I eventually found out lol.
Because I genuinely forgot most of these tend to graphical differences and such depending on the region

but yeah. revisions and games that don't have major changes depending on the region should REALLY share the screenshot. but then again stuff like different revisions nobody knew about and prototypes and such keep getting discovered so that's probably the reason different screenshots exist (Looking at you Revenge of Shinobi where every rerelease has had SOME change in them... in terms of graphics)

overall eventually I'll get my thumbnails to share the same gameplay with their regional counterparts.

**Pull request merged**
